config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :expenses
  end

  devise_for :admins
  
  root "statics#index"

  resources :pages, :controller => :statics, only: [:index, :show] do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end

  resources :contacts, only: [:index, :create] do
    collection do
      get :fetch_tours_detail
    end
  end
  
  resources :departures do
    collection do
      get :fetch_departures_detail
    end
  end

  namespace :admin do

    authenticated :admin do
      root "tours#index"#, :as => :authenticated_root
    end

    resources :admins 

    resources :contacts, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end

    resources :tours do 
      resources :departures
    end

    resources :departures do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end

  end

  get '(*url)'   => 'errors#index'
  
end

app/models/departure.rb
class Departure < ActiveRecord::Base

  belongs_to :tour

  before_validation :check_attrs

  validates_presence_of :name, :url, :filter_type
  validates_format_of :url, :with => URI::regexp(%w(http https))
  validate :url_has_drifters_domain

  paginates_per 10

  private

  def check_attrs
    self.url = URI.encode(self.url) unless json_url_valid?(self.url)
  end
  
  def url_has_drifters_domain
    uri = URI.parse(url)
    if uri
      if uri.host != 'drifters.acitravel.co.za'
        errors[:url] << "host is not permitted."
        return false
      end
    end
  end

  def json_url_valid?(url)
    
    return !!URI.parse(url)

    rescue URI::InvalidURIError
      return false
  end

end

app/controllers/admin/departures_controller.rb
#encoding: utf-8
class Admin::DeparturesController < AdminController
  
  before_action :set_tour
  before_action :set_departure, only: [:edit, :update, :destroy]

  def index
    @departures = Departure.where(tour_id: params[:tour_id]).order(:ranking) if Tour.where(id: params[:tour_id])
  end

  def new
    @departure = Departure.new
    @tours = Tour.order(:ranking)
  end

  def create
    @departure = Departure.new(departure_params)

    respond_to do |format|
      if @departure.save
        format.html { redirect_to admin_tour_departures_path(@tour), notice: 'successfully created.' }
      else
        @tours = Tour.order(:ranking)
        flash.now[:notice] = @departure.errors.full_messages 
        format.html { render :new }
      end
    end

  end
  
  def edit 
    @tours = Tour.order(created_at: :desc)
  end

  def update

    @departure.update(departure_params) 
    
    respond_to do |format|
      if @departure.save
        format.html { redirect_to edit_admin_tour_departure_path(@tour,@departure), notice: '更新成功' }
      else
        @tours = Tour.order(created_at: :desc)
        flash.now[:notice] = @departure.errors.full_messages
        format.html { render :edit }
      end      
    end
  end

  def destroy

    @departure.destroy
    
    redirect_to :back
  end

  def reorder
    errorFlag = false
    params[:departures][:reorderset].each_with_index do | departureid , index |
      the_departure = Departure.find(departureid)
      if !the_departure.nil?
        the_departure.update_attribute(:ranking , index+1 )
      else
        errorFlag = true
      end
    end

    respond_to do |format|
      if errorFlag
        format.json { head :no_content }
      else
        flash[:notice] = "重新排序成功"
        format.json do render json: flash end
      end
    end

  end  

  private
  def set_tour
    @tour = Tour.find_by_id(params[:tour_id])
  end

  def set_departure
    @departure = Departure.find_by_id(params[:id])
  end

  def departure_params
    params.require(:departure).permit(:name, :filter_type, :url, :tour_id)
  end

end

app/controllers/departures_controller.rb
#encoding: utf-8
class DeparturesController < ApplicationController
  
  def fetch_departures_detail
    begin
      if params[:looking_for].in? Tour.order(:ranking).pluck(:en_name)
        @en_name = params[:looking_for].to_s
        @limit = 12
      end

      respond_to do |format|
        format.js
      end

    rescue
      redirect_to root_path
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  # def departure_params  
  #   params.require(:departure).permit({:subject =>[]}, :name, :email, :phone, :address, :gender, :departure_date, :content)
  # end
end

app/helpers/departures_helper.rb
#encoding: utf-8
module DeparturesHelper

  def get_departure_type(departure)
    
    case departure.filter_type
      when "1"
        type = "所有(不分類)"
      when "2"
        type = "到年底"
      when "3"
        type = "明年出發"
      else
        type = "ERR"
    end
    
  end

end

app/views/admin/departures/edit.html.erb
<header>
  <h2 class="left">出團資訊<span>/ <%= "#{@departure.name}-#{@tour.name}"%></span></h2>  
  <nav class="left">
    
  </nav>
</header>
<article>  
  <%= form_for(@departure, :url => admin_tour_departure_path(@tour, @departure), html: { id: "patchthisdeparture" } ) do |f| %>
    <div class="form">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="9%">名稱：</td>
          <td width="40%">
            <%= f.text_field :name , class: 'text' %><br>
          </td>
          <td width="2%">&nbsp;</td>
          <td width="9%">篩選：</td>
          <td width="40%">
            <%= f.select :filter_type, options_for_select([['-- 請選擇 --',nil],['所有(不分類)','1'], ['到年底', '2'], ['明年出發','3']], @departure.filter_type), class: 'form-control' %>
            <br>
          </td>
        </tr>
        <tr>
          <td>URL：</td>
          <td colspan="4">
            <%= f.text_field :url , class: 'text' %><br>
          </td>
        </tr>
        <!-- <tr>
          <td valign="top">Tour：</td>
          <td colspan="4"> -->
            <%# f.select :tour_id, options_from_collection_for_select(@tours ,
              "id", "name" ) ,{:prompt => '-- 請選擇 --'}, class: 'form-control' %>
          <!-- </td>
        </tr> -->
      </table>
    </div>
    <!--form-->
    <div class="button"> 
      <%= link_to image_tag("/images/admin/left.png")+"返回", admin_tour_departures_path(@tour), class: "left" %>
      <%= content_tag :button, type: :submit, class: 'right highlight' do %>
        儲存<img src="/images/admin/save.png">
      <% end %>
    </div>
  <% end %>  
</article>

<script type="text/javascript">

</script>

app/views/admin/departures/index.html.erb
<header>
  <h2 class="left">出團資訊 <span>(可拖拉排序)</span></h2>
</header>

<article> 
  <div class="hgroup">
    <div class="button right">
      <%= link_to new_admin_tour_departure_path, class: 'right highlight toggle_new_category' do %>
        建立行程<img src="/images/admin/add_folder.png">
      <% end %>
    </div>
  </div>

  <div class="list">
    <table id='dragable_container' width="100%" border="0" cellspacing="0" cellpadding="0">
      
      <% @departures.each do |departure| %>
      
        <tr <%= "id=Departurecontainer_#{departure.id.to_s}" %> class='dragable' >
          <td width="18%">
            <%= get_departure_type(departure) %>
          </td>
          <td width="70%">
            <%= departure.name %>
          </td>
          </td>
          <td width="12%">
            <div class="tool">
              <%= link_to "", edit_admin_tour_departure_path(departure.tour, departure), class: 'edit'  %>
              <%= link_to "", admin_tour_departure_path(departure.tour,departure), :method => :delete, :data => {:confirm => "確定刪除？"}, class: "delete" %>
            </div>
          </td>
        </tr>
      <% end %>
    </table>   
  </div>
  <div class="button"> 
    <%= link_to image_tag("/images/admin/left.png")+"返回", admin_tours_path(), class: "left" %>
  </div>
</article>
 <script>
  $(function() {
    var prevEvent = null;
      $( "#dragable_container" ).sortable({
        items: ".dragable" ,
        placeholder: "ui-state-highlight",
        update: function( event, ui ) {
            
          if(event.timeStamp == prevEvent){
            return null;
          }
          
          prevEvent = event.timeStamp;  
          var newRankings_array = $('#dragable_container').sortable('toArray');
          var orderSet = [];
          $.each(newRankings_array, function( index, value){
                orderSet.push(value.replace("Departurecontainer_",""));
            });
            var order2Push = JSON.stringify(orderSet);
            
            $.ajaxSetup({
              headers: {
                  'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
          });

          // reorder 
          $.ajax({
            type: "PATCH",
            url: "/admin/departures/"+orderSet[0]+"/reorder",
            data: { departures: {  reorderset: orderSet } },
            success: function(data){

              alertify['success'](data[0][1], 2000);
              
              return false   
            },
            error: function(data){
            
              return false  
            }
          });

        }
      });
      
        
      $( "#dragable_container" ).disableSelection();
    });  
  </script>

app/views/admin/departures/new.html.erb
<header>
  <h2 class="left">出團資訊<span>/ <%= "#{@tour.name}"%></span></h2>  
  <nav class="left">
    
  </nav>
</header>
<article>
  
    <%= form_for(@departure, :url => admin_tour_departures_path(@tour), html: { id: "newthisdeparture" } ) do |f| %>
    <div class="form">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="9%">名稱：</td>
          <td width="40%">
            <%= f.text_field :name , class: 'text' %><br>
          </td>
          <td width="2%">&nbsp;</td>
          <td width="9%">篩選：</td>
          <td width="40%">
            <%= f.select :filter_type, options_for_select([['-- 請選擇 --',nil],['所有(不分類)','1'], ['到年底', '2'], ['明年出發','3']], nil), class: 'text' %>
            <br>
          </td>
        </tr>
        <tr>
          <td>URL：</td>
          <td colspan="4">
            <%= f.text_field :url , class: 'text' %>
            <%= f.hidden_field :tour_id, value: @tour.id %>
            <%# f.select :tour_id, options_from_collection_for_select(@tours ,
                  "id", "name", @tour.id ) ,{:prompt => '-- 請選擇 --'}, class: 'text' %>
          </td>
        </tr>
      </table>
    </div>
    <!--form-->
    <div class="button"> 
      <%= link_to image_tag("/images/admin/left.png")+"返回", admin_tour_departures_path(@tour), class: "left" %>
      <%= content_tag :button, type: :submit, class: 'right highlight' do %>
          儲存<img src="/images/admin/save.png">
      <% end %>
    </div>

  <% end %>
</article>

<script type="text/javascript">

</script>