config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :expenses
  end

  devise_for :admins
  
  root "statics#index"

  resources :pages, :controller => :statics, only: [:index, :show] do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end

  resources :contacts, only: [:index, :create] do
    collection do
      get :fetch_tours_detail
    end
  end
  
  resources :departures do
    collection do
      get :fetch_departures_detail
    end
  end

  namespace :admin do

    authenticated :admin do
      root "tours#index"#, :as => :authenticated_root
    end

    resources :admins 

    resources :contacts, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end

    resources :tours do 
      resources :departures
    end

    resources :departures do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end

  end

  get '(*url)'   => 'errors#index'
  
end

app/views/admin/common/_nav.html.erb
<nav class="left">
  <ul>
    <li>
      <%= link_to admin_contacts_path do %>
        <img src="/images/admin/contact.png">聯絡我們
      <% end %>
    </li>
    <li>
      <%= link_to admin_tours_path do %>
        <img src="/images/admin/news.png">出團資訊
      <% end %>
    </li>
    <li>
      <%= link_to admin_expenses_path do %>
        <img src="/images/admin/dollar.png">行程費用
      <% end %>
    </li>
  </ul>
  <ul>
  <li>
      <%= link_to admin_admins_path do %>
        <img src="/images/admin/manager.png">管理者
      <% end %>
    </li>
  </ul>
</nav>

app/views/admin/common/_show_by_type.html.erb
<%# VAR %>
<%# target_title: display name for user %>
<%# target: object %>
<%# type: gallery type %>
<div class="hgroup">
  <h3 class="left">圖片預覽 <% if allow_dragable %><span>(可拖拉排序，第一張為封面)</span><% end %></h3>          
</div>

<div class="gallery" id="listAttachs">

  <% target.galleries.select{ |v| v['type'] == type }.each_with_index do |attach, i| %>
    <% if i == 0 %>
      <div class="thumb left cover Attachcontainer dragable" <%= "id=Attachcontainer_#{attach.id.to_s}" %>> 
    <% else %>
      <div class="thumb left Attachcontainer dragable" <%= "id=Attachcontainer_#{attach.id.to_s}" %>> 
    <% end %>
    <image src=<%= "#{attach.attachment.url}" %> />

    <%= link_to '', admin_gallery_path(attach.id), method: :delete, data: { confirm: '確認刪除?' }, class: 'delete', title: '刪除' %>
    </div>
  <% end %>

</div>

<% if allow_dragable %>
<script>
  $(function() {
    var prevEvent = null;
      $( "#listAttachs" ).sortable({
        //connectWith: ".renamelevelcontainer",
        items: "> .dragable" ,
        placeholder: "ui-state-highlight",
        update: function( event, ui ) {
            
          if(event.timeStamp == prevEvent){
            return null;
          }
          
          prevEvent = event.timeStamp;  
          var newRankings_array = $('#listAttachs').sortable('toArray');
          var orderSet = [];
          $.each(newRankings_array, function( index, value){
                orderSet.push(value.replace("Attachcontainer_",""));
            });
            var order2Push = JSON.stringify(orderSet);
            
            $.ajaxSetup({
              headers: {
                  'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
          });

          //multiple reorder 
          $.ajax({
            type: "PATCH",
            url: "/admin/galleries/"+orderSet[0]+"/multiple_reorder",
            data: { gallerries: {  reorderset: orderSet } },
            success: function(data){
              $("#listAttachs > .thumb").attr('class', 'thumb left Attachcontainer dragable');
              $("#listAttachs > .thumb:first").attr('class', 'cover thumb left Attachcontainer dragable');
              alertify['success'](data[0][1], 2000);
              
              return false   
            },
            error: function(data){
            
              return false  
            }
          });

        }
      });
      
        
      $( "#listAttachs" ).disableSelection();
    });  
</script>
<% end %>

app/views/admin/common/_show_document_by_type.html.erb
<%# VAR %>
<%# target_title: display name for user %>
<%# target: object %>
<%# type: gallery type %>

<div class="form">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td width="7%"><%= target_title %>：</td>
      <td width="93%">
        <div class="thumb">
          <% target.galleries.select{ |v| v['type'] == type }.each do |attach| %>
            <%= link_to "#{attach.file_name}", attach.attachment.url, target: '_blank' %>
            <%= link_to '刪除', admin_gallery_path(attach.id), method: :delete, data: { confirm: '確認刪除?' }, class: 'delete', title: '刪除' %>
          <% end %>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/admin/common/_upload_by_type.html.erb
<%# VAR %>
<%# target_title: display name for user %>
<%# target: object %>
<%# target_controller: controller name %>
<%# type: gallery type %>

<div class="form">
  
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td width="7%"><%= target_title %>：</td>
      <td width="93%">
        <!-- COVER UPLOAD -->
        <%= file_field_tag :attachment, class: 'file' %>
      </td>
    </tr>
  </table>
  
</div>

app/views/admin/common/_upload_document_by_type.html.erb
<%# VAR %>
<%# target_title: display name for user %>
<%# target: object %>
<%# target_controller: controller name %>
<%# type: gallery type %>

<div class="form">
  
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td width="7%"><%= target_title %>：</td>
      <td width="93%">
        <%= text_field_tag 'filename', nil, placeholder: '附件顯示名稱', class: 'text' %>
        <!-- COVER UPLOAD -->
        <%= file_field_tag :attachment, class: 'file' %>
      </td>
    </tr>
  </table>
  
</div>