config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :expenses
  end

  devise_for :admins
  
  root "statics#index"

  resources :pages, :controller => :statics, only: [:index, :show] do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end

  resources :contacts, only: [:index, :create] do
    collection do
      get :fetch_tours_detail
    end
  end
  
  resources :departures do
    collection do
      get :fetch_departures_detail
    end
  end

  namespace :admin do

    authenticated :admin do
      root "tours#index"#, :as => :authenticated_root
    end

    resources :admins 

    resources :contacts, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end

    resources :tours do 
      resources :departures
    end

    resources :departures do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end

  end

  get '(*url)'   => 'errors#index'
  
end

app/views/admin/admins/edit.html.erb
  <header>
      <h2>Edit profile</h2>      
    </header>
    <article>              
        <div class="form">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <%= form_for(@admin,:url => admin_admin_path, :html => {:id =>'EditAdminForm' , :method => "PATCH"} ) do | f |%>
            <tr>
              <td width="6%">姓名：</td>
              <td width="40%"><%= f.text_field :name, class: 'text' %></td>
              <td width="4%">&nbsp;</td>
              <td width="10%">Email：</td>
              <td width="40%"><%= f.text_field :email, class: 'text' %></td>
            </tr>
            <tr>
              <td>密碼：</td>
              <td><%= f.password_field :password, class: 'text'  %></td>
              <td>&nbsp;</td>
              <td>確認密碼：</td>
              <td><%= f.password_field :password_confirmation, class: 'text'  %></td>
            </tr>
            <% end %>
          </table>
        </div>
		
		
      <div class="button">
      	<%= link_to image_tag("/images/admin/left.png")+"返回", admin_admins_path(), class: "left" %>
      	<a href='javascript:void(0);' class='right highlight'  onclick= "$('#EditAdminForm').submit()">變更
          <img src="/images/admin/add.png">
        </a>
      </div>
    <!--button--> 

app/views/admin/admins/index.html.erb
  <header>
    <h2>管理者</h2>      
  </header>
  <article>           
      <div class="form">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <%= form_for(@admin,:url => admin_admins_path, :html => {:id =>'NewAdminForm' , :method => "post"} ) do | f |%>
            <tr>
              <td width="6%">姓名：</td>
              <td width="40%"><%= f.text_field :name, class: 'text' %></td>
              <td width="4%">&nbsp;</td>
              <td width="10%">Email：</td>
              <td width="40%"><%= f.text_field :email, class: 'text' %></td>
            </tr>
            <tr>
              <td>密碼：</td>
              <td><%= f.password_field :password, class: 'text'  %></td>
              <td>&nbsp;</td>
              <td>確認密碼：</td>
              <td><%= f.password_field :password_confirmation, class: 'text'  %></td>
            </tr>
          <% end %>
        </table>
        
      </div>
  
    <div class="button"> 
      <a href='javascript:void(0);' class='right highlight'  onclick= "$('#NewAdminForm').submit()">新增管理員<img src="/images/admin/add.png"></a>
      </div>
    </div>
    <div class="list">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <% @admins.each do | admin | %>   
       
            <tr>
              <td width="16%"></td>
              <td width="18%"><%= admin.name %></td>
              <td width="54"><%= admin.email %></td>
              <td width="12%">
                  <div class="tool">
                      <a href="<%= edit_admin_admin_path(admin) %>" class="edit" title="編輯"></a><%= link_to '', admin_admin_path( admin ), :method => :delete, class: "delete", title: "刪除", data: { confirm: "是否確定刪除使用者#{admin.name}? 此動作無法復原。" } %>
                  </div>
               </td>
            </tr>
           
        <% end %>
      </table>
    </div>      
  </article>