config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :expenses
  end

  devise_for :admins
  
  root "statics#index"

  resources :pages, :controller => :statics, only: [:index, :show] do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end

  resources :contacts, only: [:index, :create] do
    collection do
      get :fetch_tours_detail
    end
  end
  
  resources :departures do
    collection do
      get :fetch_departures_detail
    end
  end

  namespace :admin do

    authenticated :admin do
      root "tours#index"#, :as => :authenticated_root
    end

    resources :admins 

    resources :contacts, :only => [:index, :update] do
      collection do 
        get 'history', action: 'history'
      end
    end

    resources :tours do 
      resources :departures
    end

    resources :departures do 
      member do
        patch 'reorder' , :action => 'reorder'
      end 
    end

  end

  get '(*url)'   => 'errors#index'
  
end

app/views/layouts/_front_shared_footer.html.erb
<footer>
  <div class="container row">
    <div class="col-sm-3 col-sm-offset-2" id="link">
      <div id="link-1"> <%= link_to "立刻報名", contacts_path, 'data-no-turbolink' => true %> </div>
      <div id="link-2"> <a href="https://www.instagram.com/drifterstw" target="_blank"><img src="/images/fot-08.gif" class="img-responsive"><br>
        Instagram</a><a href="https://www.facebook.com/drifters.tw" target="_blank"><img src="/images/fot-07.gif" class="img-responsive"><br>
        Facebook</a> </div>
    </div>
    <div class="col-sm-4 col-sm-offset-2 text-right" id="info"> <a href="mailto:info@drifters.com.tw" target="_blank"><img src="/images/fot-04.png">info@drifters.com.tw</a><br>
      TEL: <a href="tel:+886223961768">(02) 2396-1768</a><br>
      FAX: (02) 2392-7058<br>
      台北市中正區忠孝東路二段 112 號 5 樓<br>
      <br>
      <br>
      <br>
      Copyright © All Rights Reserved. </div>
    <div id="gotop"><a href="#header"><img src="/images/fot-03.png" class="img-responsive"></div>
  </div>
</footer> 

app/views/layouts/_front_shared_header.html.erb
<header id="header">
  <div class="clearfix container">
    <h1><%= link_to '大旅行家', root_url %></h1>
    <nav class="navbar" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"> <img src="/images/hdr-ctrl.gif" class="img-responsive"> </button>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="visible-xs"><%= link_to '回首頁', root_url %></li>
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">旅程特色</a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "自己做主", page_pages_path('liberty'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "一網打盡所有奇觀", page_pages_path('wonders'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "體驗式學習", page_pages_path('experience'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "深入非洲核心", page_pages_path('core'), 'data-no-turbolink' => true %></li>
            </ul>
          </li>
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">經典行程</a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "南非克魯格灌叢草原 5 天", page_pages_path('KrugerPark5day'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "南非生態探索之旅 18 天", page_pages_path('SouthAfrica18day'), 'data-no-turbolink' => true %></li>
            </ul>
          </li>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">探險行程</a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "納米比亞秘境野營 17 天", page_pages_path('Namibia17day'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "烏干達越野探索 12 天", page_pages_path('Uganda12day'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "東非越野獵遊 12 天", page_pages_path('EastAfrica12day'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "莫三比克海陸探索 14 天", page_pages_path('Mozambique14day'), 'data-no-turbolink' => true %></li>
            </ul>
          </li>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">冒險行程</a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "波札那獵遊野營 16 天", page_pages_path('Botswana16day'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "辛巴威越野露營獵遊 16 天", page_pages_path('Zimbabwe16day'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "南部非洲巡弋 24 天", page_pages_path('SouthernCruise24day'), 'data-no-turbolink' => true %></li>
              <li><%= link_to "周遊南部非洲 24 天", page_pages_path('SouthernCircle24day'), 'data-no-turbolink' => true %></li>
            </ul>
          </li>
          <li><%= link_to "立刻報名", contacts_path, 'data-no-turbolink' => true %></li>
        </ul>
      </div>
    </nav>
  </div>
  <!--container-->
  <div id="banner"></div>
</header>

app/views/layouts/admin.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />
<title>大旅行家後台管理系統</title>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<!-- Bootstrap -->
<link rel="stylesheet" href="/css/admin/reset.css">
<link rel="stylesheet/less" type="text/css" href="/css/admin/global.less" />
<link rel="stylesheet/less" type="text/css" href="/css/admin/custom.less" />
<script src="/js/admin/less.min.js"></script>
<script src="/js/admin/global.js"></script>
<script>
  window.onload= function() {
  <% if !flash[:notice].nil? %>
   alertify['success']('<%= flash[:notice] %>', 3000);
  <% end %>
  
  <% if !flash[:alert].nil? %>
  alertify['error']("<%= flash[:alert].html_safe %>", 3000); 
  <% end %>
}
</script>
</head>
<body>

  <section id="wrapper">
    <header>
      <h1>大旅行家後台管理系統</h1>
      <aside class="right"> <a href="<%= admin_root_url %>" id="aside-1">index</a><%= link_to "Edit profile", admin_admins_path , id: "aside-2" %><%= link_to 'Log out', destroy_admin_session_path, :method => :delete, id: "aside-3" %></aside>
    </header>

    <article id="container">
      
      <%= render 'admin/common/nav' %>
      
      <section id="content" _height="auto" class="left">
        <%= yield %>    
      </section>

    </article>

  </section>

</body>
</html>

app/views/layouts/admin_sign_in.html.erb
<!doctype html>
<html>
<head>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<![endif]-->
<meta charset="utf-8">
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />
<title>大旅行家後台管理系統</title>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<!-- Bootstrap -->
<link rel="stylesheet" href="/css/admin/reset.css">
<link rel="stylesheet/less" type="text/css" href="/css/admin/login.less" />

<script src="/js/admin/less.min.js"></script>
<script src="/js/admin/global.js"></script>

</head>

<body>

<%= yield %>

<div id="footer" _height="none"> Copyright © Summers </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-tw">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="keywords" content="">
<link href='/images/favicon.ico' rel='shortcut icon' />
<link href="/images/favicon.ico" rel="icon" type="image/x-icon" />
<link rel="shortcut icon" href="/images/favicon.ico" type="image/vnd.microsoft.icon">
<link rel="icon" href="/images/favicon.ico" type="image/vnd.microsoft.icon">
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<title>大旅行家 Drifters - 帶你深入非洲</title>
<meta name="keywords" content="大旅行家,非洲旅行團,非洲旅遊,寶崴旅行社,寶崴,維多利亞瀑布旅遊,東非旅遊,南非旅遊,非洲自由行,非洲半自助,drifters,Drifters Truck,探險旅遊,卡車旅遊,獵遊,國外旅遊,國外旅遊推薦,旅遊行程,納米比亞沙漠旅遊,奧卡萬戈旅遊,克魯格國家公園,非洲草原旅遊,非洲卡車,非洲動物旅遊,烏干達旅遊,莫三比克旅遊,辛巴威旅遊,波札那旅遊,非洲野生動物旅遊,冒險旅遊,動物大遷徙旅遊,非洲露營,非洲背包客,非洲越野車旅遊"/>
<meta name="description" content="大旅行家越野系列深入非洲原始蠻荒地帶，遠離文明，如果你喜歡冒險，喜歡用新生兒的眼光看世界，汲取最獨一無二的經驗，大旅行家越野系列將帶給你超越五星級的收穫與體驗。" />
<meta property="og:site_name" content="大旅行家 Drifters - 帶你深入非洲"/>
<meta property="og:title" content="大旅行家 Drifters - 帶你深入非洲"/>
<meta property="og:description" content="大旅行家越野系列深入非洲原始蠻荒地帶，遠離文明，如果你喜歡冒險，喜歡用新生兒的眼光看世界，汲取最獨一無二的經驗，大旅行家越野系列將帶給你超越五星級的收穫與體驗。"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="http://www.drifters.com.tw"/>
<meta property="og:image" content="http://www.drifters.com.tw/images/thumb.jpg">
<link rel="image_src" href="http://www.drifters.com.tw/images/thumb.jpg">
<!-- Bootstrap -->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<script>
window.onload= function() {
  <% if !flash[:notice].nil? %>
   alertify['success']('<%= flash[:notice] %>', 2000);
  <% end %>
  
  <% if !flash[:alert].nil? %>
  alertify['error']("<%= flash[:alert].html_safe %>", 2000); 
  <% end %>
}
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56172097-1', 'auto');
  ga('send', 'pageview');

</script>
<script>
var dpWidth = $(window).width();

$(window).resize(function(){
  dpWidth = $(window).width();
});

$(document).ready(function() {
  $('.dropdown').hover(function(){
    if( dpWidth > 1024 ){
      $(this).children('.dropdown-menu').stop().slideDown(200);
    }
  },function(){
    if( dpWidth > 1024 ){
      $(this).children('.dropdown-menu').stop().slideUp(100);
    }
  })
  $('.dropdown').click(function(){
    if( dpWidth < 1024 ){
      $(this).siblings().children('.dropdown-menu').hide();
      $(this).children('.dropdown-menu').stop().toggle(0);
    }
  })
})
</script>
</head>
<body>

<%= render 'layouts/front_shared_header' %>

<%= yield %>

<%= render 'layouts/front_shared_footer' %>

<!-- Include all compiled plugins (below), or include individual files as needed --> 
<script src="/js/bootstrap.min.js"></script> 
<script src="/js/mousewheel.js"></script>
<script src="/js/jquery.parallax-1.1.3.js"></script> 
<script src="/js/anchor-art.js"></script> 
<script src="/js/jquery.bxslider.min.js"></script> 
<script> localStorage.clear();</script>
</body>
</html>